print('===== DESAFIO #002 =====')
print('Insira os seguintes dados da sua data de nascimento:')
dia = input('Dia: ')
mes = input('Mês: ')
ano = input('Ano: ')
print('Você nasceu no dia ' + dia + '/' + mes + '/' + ano + '. Correto?')
